sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shred86/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shred86/docker-react npm run test