sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shred86/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shred86/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-633802009576"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY